
DROP TABLE DVENTA;
DROP TABLE ARTICULO;
DROP TABLE VENTA;
DROP TABLE TRABAJADOR;
DROP TABLE CLIENTE;
DROP TABLE UMEDIDA;

CREATE TABLE UMEDIDA (
	UMedidaId NCHAR ( 5 ) NOT NULL,
	Nombre NVARCHAR ( 30 ) NOT NULL,
	Descripcion NVARCHAR ( 50 ) NOT NULL,
	CONSTRAINT PK_UMEDIDA17 PRIMARY KEY NONCLUSTERED (UMedidaId)
	)
GO
CREATE TABLE DVENTA (
	DVentaId NCHAR ( 5 ) NOT NULL,
	Cantidad INT NOT NULL,
	Precio FLOAT ( 38 ) NOT NULL,
	VentaId NCHAR ( 5 ) NOT NULL,
	ArticuloId NCHAR ( 5 ) NOT NULL,
	CONSTRAINT PK_DVENTA16 PRIMARY KEY NONCLUSTERED (VentaId, DVentaId)
	)
GO
CREATE INDEX TC_DVENTA35 ON DVENTA (ArticuloId )
GO
CREATE INDEX TC_DVENTA34 ON DVENTA (VentaId )
GO
CREATE TABLE TRABAJADOR (
	TrabajadorId NCHAR ( 5 ) NOT NULL,
	Apellidos NVARCHAR ( 30 ) NOT NULL,
	Nombres NVARCHAR ( 30 ) NOT NULL,
	Cargo NVARCHAR ( 30 ) NOT NULL,
	Dni NVARCHAR ( 8 ) NOT NULL,
	Celular NVARCHAR ( 15 ) NOT NULL,
	Direccion NVARCHAR ( 50 ) NOT NULL,
	Email NVARCHAR ( 40 ) NOT NULL,
	Imagen NVARCHAR ( 1000 ) NOT NULL,
	CONSTRAINT PK_TRABAJADOR13 PRIMARY KEY NONCLUSTERED (TrabajadorId)
	)
GO
CREATE TABLE ARTICULO (
	ArticuloId NCHAR ( 5 ) NOT NULL,
	Nombre NVARCHAR ( 30 ) NOT NULL,
	Descripcion NVARCHAR ( 50 ) NOT NULL,
	Cantidad INT NOT NULL,
	Precio FLOAT ( 38 ) NOT NULL,
	Imagen NVARCHAR ( 1000 ) NOT NULL,
	UMedidaId NCHAR ( 5 ) NOT NULL,
	CONSTRAINT PK_ARTICULO15 PRIMARY KEY NONCLUSTERED (ArticuloId)
	)
GO
CREATE INDEX TC_ARTICULO33 ON ARTICULO (UMedidaId )
GO
CREATE TABLE VENTA (
	VentaId NCHAR ( 5 ) NOT NULL,
	Fecha DATETIME NOT NULL,
	Comentario NVARCHAR ( 100 ) NOT NULL,
	ClienteId NCHAR ( 5 ) NOT NULL,
	TrabajadorId NCHAR ( 5 ) NOT NULL,
	CONSTRAINT PK_VENTA14 PRIMARY KEY NONCLUSTERED (VentaId)
	)
GO
CREATE INDEX TC_VENTA32 ON VENTA (ClienteId )
GO
CREATE INDEX TC_VENTA31 ON VENTA (TrabajadorId )
GO
CREATE TABLE CLIENTE (
	ClienteId NCHAR ( 5 ) NOT NULL,
	Apellidos NVARCHAR ( 30 ) NOT NULL,
	Nombres NVARCHAR ( 30 ) NOT NULL,
	Celular NVARCHAR ( 15 ) NOT NULL,
	Direccion NVARCHAR ( 50 ) NOT NULL,
	Email NVARCHAR ( 40 ) NOT NULL,
	Imagen NVARCHAR ( 1000 ) NOT NULL,
	CONSTRAINT PK_CLIENTE12 PRIMARY KEY NONCLUSTERED (ClienteId)
	)
GO
ALTER TABLE VENTA ADD CONSTRAINT FK_VENTA12 FOREIGN KEY (TrabajadorId) REFERENCES TRABAJADOR (TrabajadorId) 
GO
ALTER TABLE VENTA ADD CONSTRAINT FK_VENTA11 FOREIGN KEY (ClienteId) REFERENCES CLIENTE (ClienteId) 
GO
ALTER TABLE ARTICULO ADD CONSTRAINT FK_ARTICULO15 FOREIGN KEY (UMedidaId) REFERENCES UMEDIDA (UMedidaId) 
GO
ALTER TABLE DVENTA ADD CONSTRAINT FK_DVENTA13 FOREIGN KEY (VentaId) REFERENCES VENTA (VentaId) 
GO
ALTER TABLE DVENTA ADD CONSTRAINT FK_DVENTA14 FOREIGN KEY (ArticuloId) REFERENCES ARTICULO (ArticuloId) 
GO

